[env]
TUIST_CACHE_CONFIGURATION = "Debug"
TUIST_CACHE_PROFILE = "only-external"
XCODE_APP_SCHEME = "MyApp"
IOS_SIMULATOR_NAME = "iPhone 17"
TESTFLIGHT_GROUPS = "Internal, External"

[settings]
lockfile = true
lockfile_platforms = ["macos-arm64"]
locked_verify_provenance = false

[tools]
"aqua:jdx/usage" = "3.5.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:koalaman/shellcheck" = "0.11.0"
